name: book_store_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #firebase
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_database: ^3.1.6
  flutter:
    sdk: flutter
  #icon
  font_awesome_flutter: ^8.8.1
  #font
  google_fonts: ^1.1.0
  #design
  curved_navigation_bar: ^0.3.3


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

fonts:  
   - family: Tajawal  
     fonts:  
       - asset: fonts/Tajawal-Medium.ttf 