name: book_store_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^4.0.0    
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+2
  splashscreen: ^1.2.0
  curved_navigation_bar: ^0.3.3
  http: ^0.12.1
  shared_preferences: ^0.5.8
  flutter_redux: ^0.6.0
  redux: ^4.0.0+3 
  rxdart: ^0.25.0
  provider: ^4.3.2+3
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/

       